### ISSUE TITLE
Support global normalisation, rather than only per-tile normalisation

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath-extension-stardist#20]
See discussion at https://github.com/qupath/2022-qupath-hackathon/discussions/6

**Comment by lacan** [comment]
One suggestion would be to rename 

`preprocess(TileOpCreator global)` to 

`preprocessGlobal(TileOpCreator global)` to avoid confusion with the `preprocess(ImageOp... ops)` which is per tile.

While it is quite clear from the documentation, basing the behaviour only on the argument type feels risky. 

https://github.com/qupath/qupath-extension-stardist/blob/09824389eae116c37ba8951e856dd546224e05c9/src/main/java/qupath/ext/stardist/StarDist2D.java#L210

**Comment by petebankhead** [comment]
Thanks @lacan I've made that change now and deprecated the old method. It should still work for now, but logs a warning the first time it is used.
