### ISSUE TITLE
Tile artifacts under some circumstances

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath-extension-stardist#5]
## Bug report

**Describe the bug**
Tile artifacts appear under some circumstances. See
* https://forum.image.sc/t/thoughts-on-0-3-2-rc2-with-stardist/56481
* https://forum.image.sc/t/qupath-v0-3-0-release-candidate-2/56185/4

**To Reproduce**
Not sure yet...

**Expected behavior**
No obvious tile artifacts.

**Version**
 - v0.3.0-rc2

**Additional context**
Almost certainly due to the lack of padding since https://github.com/qupath/qupath-extension-stardist/commit/b09a16ef59384b5a39b87e9f17e31da04b19ef29
However, reinstating padding may not be entirely straightforward because of how tile requests are handled.

**Comment by petebankhead** [comment]
This should be resolved in the v0.3.0 release.

**Comment by gil-c** [comment]
Hi Pete,

A colleague of mine used the version 0.3.0 release from here: https://github.com/qupath/qupath/releases/tag/v0.3.0 and found the same artifact as described by other users.

Is the fix you mentioned supposed to be in this binaries?

**Comment by melvingelbard** [comment]
@gil-c ,
Have they tried the last version of `qupath-extension-stardist`? ([This one](https://github.com/qupath/qupath-extension-stardist/releases/tag/v0.3.0))

**Comment by petebankhead** [comment]
@gil-c as @melvingelbard suggests, the fix is in the extension - not in QuPath. So you're colleague would need the latest version of the extension.

Here is the forum discussion that explores the fix https://forum.image.sc/t/error-running-stardist-on-qupath-v0-3-0-rc2-using-opencv-converted-model/56216/39 so as far as I am aware it has been fully addressed.

There may still be tiling artefacts due to different normalization per tile, but that would be a different issue - and not really a bug in the extension but rather a discussion topic for the forum (since different kinds of normalization can be applied).

**Comment by gil-c** [comment]
Indeed, it is the version of the plugin that was not up to date on our side. Now everything works smoothly again!

Thanks @petebankhead
